languageCode = "en"
# en / zh-cn / ... (This field determines which i18n file to use)
defaultContentLanguage = "zh-cn"
title = "Songqi"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "songqi"
# 可根据 Git 中的提交生成最近更新记录。
enableGitInfo = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# 语法高亮。注意：请勿同时启用`highlightInClient`和`chroma`！
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

# 自动检测是否包含 中文\日文\韩文
hasCJKLanguage = true
# 首页每页显示的文章数
paginate = 5
# disqus_shortname
# disqusShortname = "songqi"
  disqusShortname = ""
# UA-XXXXXXXX-X
googleAnalytics = "UA-131168697-2"      
# 默认为下面配置的author.name
copyright = "Songqi Duan"

[author]
  name = "Songqi Duan"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
  
[permalinks]
  post = "/:year/:month/:day/:slug/"

# 配置目录
[[menu.main]]
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"
  
[[menu.main]]
  name = "关于"
  weight = 50
  identifier = "about"
  url = "/about/"

[params]
  # 当你有一个不兼容的更新时，会给你一个友好的信息
  version = "4.x"
  # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  debug = false

  # 站点建立时间
  since = "2020"
  # 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
  gitRepo = "git@github.com:zerostwo/songqi.git"

  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Songqi"  # 默认值: 上面设置的title值
  keywords = ["生物信息学", "R语言","数据分析","段松岐","Songqi Duan"]
  description = "Personal website of Songqi Duan"

  # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archivePaginate = 10

  # 是否在归档页显示文章的总数
  showArchiveCount = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # 是否显示字数统计与阅读时间
  moreMeta = true

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # 是否开启目录
  toc = true
  # 目录自动展开/折叠
  autoCollapseToc = true
  # 是否启用fancybox（图片可点击）
  fancybox = true

  # mathjax
  # see https://www.mathjax.org/ 
  # 是否使用mathjax（数学公式）
  mathjax = true
  # 是否使用 $...$ 即可進行inline latex渲染
  mathjaxEnableSingleDollar = true
  # 是否使用公式自动编号
  mathjaxEnableAutoNumber = true
  # You should install mathjax in `your-site/static/lib/mathjax`
  mathjaxUseLocalFiles = false

  # 包含作者，上次修改时间，markdown链接，许可信息
  postMetaInFooter = true
  # 链接到markdown原始文件（仅当允许hugo生成markdown文件时有效）
  linkToMarkDown = true
  # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # 畅言
  changyanAppid = ""
  changyanAppkey = ""

  # 来必力
  #livereUID = "MTAyMC80OTcwMC8yNjE5MQ=="                  
  livereUID = ""
  
  # 百度
  baiduPush = true        # baidu push                  
  baiduAnalytics = "0c941bf9e3385efd75dbf7ede017eb3f"      # Baidu Analytics
  baiduVerification = ""   # Baidu Verification
  # 谷歌
  googleVerification = ""  # Google Verification

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

  # please keep same with uglyurls setting
  uglyURLs = false

  # 启用公共CDN，需自行定义
  [params.publicCDN]
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJS = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
    timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
    timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
    flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
    sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
    sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [params.outdatedInfoWarning]
    enable = true
    # 如果文章最后更新于这天数之前，显示提醒
    hint = 30
    # 如果文章最后更新于这天数之前，显示警告
    warn = 180

  # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  [params.gitment]
    # Your GitHub ID
    owner = ""
    # The repo to store comments
    repo = ""
    # Your client ID
    clientId = ""
    # Your client secret
    clientSecret = ""

  # https://utteranc.es/
  [params.utterances]
    # Your GitHub ID
    owner = ""
    # The repo to store comments
    repo = ""

  # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  [params.gitalk]
    # Your GitHub ID
    owner = "zerostwo"
    # The repo to store comments
    repo = "songqi"
    # Your client ID
    clientId = "e80f8bc7b6095ab1ad40"
    # Your client secret
    clientSecret = "623211db1d4eca51644a76627aa4d2f224dd98c8"

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = true
    appId = 'EbW42Mr8CI212K4Nni3nVHGA-gzGzoHsz'
    appKey = 'NVfGGps0xGO1Jye6lY2KdSQR'
    # mail notifier , https://github.com/xCss/Valine/wiki
    notify = true
    # Verification code
    verify = true
    avatar = 'mm' 
    placeholder = '说点什么吧...'
    visitor = false
    
  # see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
  [params.flowchartDiagrams]
    enable = true
    options = ""

  # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
  [params.sequenceDiagrams] 
    enable = true
    # default: "{theme: 'simple'}"
    options = ""

  # 是否使用不蒜子统计站点访问量
  [params.busuanzi]
    enable = false
    siteUV = true
    sitePV = true
    pagePV = true

  # 文章打赏
  [params.reward]
    enable = false  
    # 微信二维码
    wechat = "/path/to/your/wechat-qr-code.png"
    # 支付宝二维码
    alipay = "/path/to/your/alipay-qr-code.png"

  # 社交链接
  [params.social]
    #a-email = "songqi.duan@outlook.com"
    #b-stack-overflow = "https://stackoverflow.com/users/13328284/duansq"
    #c-twitter = "https://twitter.com/duansongqi1999"
    #d-facebook = "https://www.facebook.com/songqi.duan/"
    #e-linkedin = "https://www.linkedin.com/in/songqi-duan-a019b6163/"
    #f-google = ""
    g-github = "https://github.com/zerostwo"
    h-weibo = "https://weibo.com/3764641951"
    i-zhihu = "https://www.zhihu.com/people/zerostwo"
    #j-douban = "https://www.douban.com/people/duansq/"
    #k-pocket = "http://localhost:1313"
    #l-tumblr = "http://localhost:1313"
    #m-instagram = "https://www.instagram.com/songqiduan/"
    #n-gitlab = "http://localhost:1313"
    o-bilibili = "https://space.bilibili.com/85834603"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    # 12.214.31.144 -> 12.214.31.0
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true

# 将下面这段配置取消注释可以使 hugo 生成 .md 文件
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
