---
title: PCA绘图
author: Songqi Duan
date: '2020-04-16'
slug: pca
categories:
  - 生物信息学
tags:
  - R
lastmod: '2020-04-16T21:52:16+08:00'
keywords: []
description: 'This'
comment: false
toc: true
autoCollapseToc: true
postMetaInFooter: true
hiddenFromHomePage: false
contentCopyright: false
reward: false
mathjax: false
mathjaxEnableSingleDollar: false
mathjaxEnableAutoNumber: false
hideHeaderAndFooter: false
flowchartDiagrams:
  enable: false
  options: ''
sequenceDiagrams:
  enable: false
  options: ''
---
使用R语言进行PCA绘图
<!--more-->

>参考[StatQuest: PCA in R](https://www.youtube.com/watch?v=0Jp4gsfOLMs&list=PLblh5JKOoLUJJpBNfk8_YadPwDTO2SCbx)

构建绘图数据
```{r}
data.matrix <- matrix(nrow=100, ncol=10)
colnames(data.matrix) <- c(
  paste("wt", 1:5, sep=""),
  paste("ko", 1:5, sep="")
)
rownames(data.matrix) <- c(
  paste("gene", 1:100, sep="")
)
for (i in 1:100) {
  wt.values <- rpois(5, lambda=sample(x=10:1000, size=1))
  ko.values <- rpois(5, lambda=sample(x=10:1000, size=1))
  data.matrix[i,] <- c(wt.values, ko.values)
}
```

`procomp`默认样本为行，基因为列，因此在这里需要转置
```{r}
pca <- prcomp(t(data.matrix), scale=TRUE)
str(pca) # return x, sdev and rotation
```

取第一主成分和第二主成分
```{r}
plot(pca$x[,1], pca$x[,2]) 
```

- 第一主成分解释了原始数据（所有10个样本的基因表达）中最大的方差

- 第二主成分解释了...第二大方差，以此类推

让我们看看PC1能解释原始数据多大的方差，因此我们使用`sdev`(标准差)的平方

标准差的平方是方差
```{r}
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
barplot(pca.var.per, 
        main="Scree Plot", xlab="Principal Component",
        ylab="Percent Variation")
```

```{r}
library(ggplot2)
pca.data <- data.frame(
  Sample=rownames(pca$x),
  X=pca$x[,1],
  Y=pca$x[,2]
)

ggplot(data=pca.data, mapping = aes(x=X, y=Y, label=Sample)) +
  geom_text() + 
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) + 
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) + 
  theme_bw() +
  ggtitle("My PCA Graph")
```

下面我们可以通过`pca$rotation`来看什么基因对结果影响最大
```{r}
loading_scores <- pca$rotation[,1] # 这里使用第一列因为PC1的对原始数据的影响达到91%
gene_scores <- abs(loading_scores)
gene_score_ranked <- sort(gene_scores, decreasing=TRUE)
top_10_genes <- names(gene_score_ranked[1:10])
top_10_genes
```

查看造成`wt`与`ko`不一样的关键基因
```{r}
pca$rotation[top_10_genes,1]
```

得到的结果说明，`PC1`下得分为正的是将`ko`推向PCA Graph右边的关键基因

为负的则是将`wt`推向左边的关键基因

说明这些基因是造成`wt`和`ko`不同的差异性表达基因
